jwt:
 audience: myapp
 issuer: mycompanyname
 secret: 4ao25ZPL/aC3lqRuDoj9RsuxLq+TtgkSAGkXFQ==jucr3j0SwCaCzNlePozoUIXl
 token-validity: 18000000 # 5*60*60*1000
 type: JWT

security:
  paths:
#    ignored:
#     - /h2-console/**
    permitted:
      - /auth/**

logging:
  level:
    root: info
    com.ashu.practice: debug
#    com.hazelcast: WARN
    #org.springframework.security.web: debug
    #org.springframework.cache: trace
server:
  servlet:
    context-path: /api/v1
  port: 8085

spring:
  application:
    name: authentication-service
#  datasource:
#    url: jdbc:postgresql://localhost/postgres
#    username: postgres
#    password: changeme
#  h2:
#    console:
#      enabled: true
#  jpa:
#    show-sql: true
  flyway:
#    enabled: false
    locations:
    - classpath:db/migration/h2
  main:
   banner-mode: off

management:
  endpoints:
    web:
      exposure:
        include: "*"

hazelcast:
  instance-name: authentication-service-instance
  map-name: authentication-service
  cluster-name: auth-service