apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
  labels:
    app: pgadmin
spec:
  selector:
    app: pgadmin
  ports:
    - port: 80
      nodePort: 31000
  type: NodePort
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin-server-config
data:
  servers.json: |
    {
    "Servers":{
        "1":{
          "Name":"Postgres kubenetes",
          "Group":"Servers",
          "Port":5432,
          "Username":"postgres",
          "Host":"postgres-service",
          "SSLMode":"prefer",
          "MaintenanceDB":"postgres"
        }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  labels:
    app: pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
        - name: pgadmin
          image: dpage/pgadmin4:6.4
          resources:
            limits:
              memory: "300Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              valueFrom:
                secretKeyRef:
                  name: pgadmin
                  key: email
            - name: PGADMIN_DEFAULT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgadmin
                  key: password
            - name: PGADMIN_SERVER_JSON_FILE
              value: /tmp/servers.json
          volumeMounts:
            - mountPath: /tmp/
              name: pgadmin-server-config
      volumes:
        - name: pgadmin-server-config
          configMap:
            name: pgadmin-server-config
