apiVersion: v1
kind: Secret
metadata:
  name: postgres-db
type: Opaque
data:
  username: cG9zdGdyZXM= #postgres
  password: Y2hhbmdlbWU= #changeme
---
apiVersion: v1
kind: Secret
metadata:
  name: pgadmin
type: Opaque
data:
  email: cGdhZG1pbkBleGFtcGxlLm9yZw== #pgadmin@example.org
  password: Y2hhbmdlbWU= #changeme