client:
  auth-service-url: http://localhost:8085/api/v1/auth

security:
  paths:
    ignored:
      #     - /h2-console/**
      - /static/**
    permitted:
      - /auth/**

logging:
  level:
    root: info
    com.ashu.practice: debug
server:
  servlet:
    context-path: /api/v1
spring:
  application:
    name: book-service
#  datasource:
#    url: jdbc:postgresql://localhost/booksdb
#    username: postgres
#    password: changeme
#  jpa:
#    hibernate:
#      ddl-auto: validate
#    show-sql: true
  flyway:
    locations:
    - classpath:db/migration/h2
  main:
    banner-mode: off

management:
  endpoints:
    web:
      exposure:
        include: "*"

hazelcast:
  instance-name: book-service-instance
  map-name: book-service
  cluster-name: book-service