apiVersion: v1
kind: Service
metadata:
  name: hazelcast-book-service
spec:
  selector:
    app: book-service
  ports:
    - name: hazelcast
      port: 5701
#  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: book-service
  labels:
    app: book-service
spec:
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 31002
  selector:
    app: book-service
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-service
  labels:
    app: book-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: book-service
  template:
    metadata:
      labels:
        app: book-service
    spec:
      containers:
        - name: book-service
          image: ashutoshsahoo/book-service
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "300Mi"
              cpu: "200m"
            limits:
              memory: "700Mi"
              cpu: "500m"
          ports:
            - name: http
              containerPort: 8080
            - name: multicast
              containerPort: 5701
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: CLIENT_AUTH_SERVICE_URL
              value: http://auth-service/api/v1/auth
            - name: HAZELCAST_SERVICE_NAME
              value: hazelcast-book-service
            - name: HAZELCAST_NAMESPACE
              value: default
            - name: HAZELCAST_DISCOVERY_TYPE
              value: kubernetes
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-service/booksdb
            - name: SPRING_FLYWAY_LOCATIONS
              value: classpath:db/migration/postgresql
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-db
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-db
                  key: password
          readinessProbe:
            httpGet:
              path: /api/v1/actuator/health/readiness
              port: http
            initialDelaySeconds: 130
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /api/v1/actuator/health/liveness
              port: http
            initialDelaySeconds: 150
            timeoutSeconds: 10
            failureThreshold: 10
