DROP TABLE IF EXISTS "USER_ROLES";
DROP TABLE IF EXISTS "ROLES";
DROP TABLE IF EXISTS "USERS";

DROP SEQUENCE IF EXISTS "USER_ID_SEQUENCE";
DROP SEQUENCE IF EXISTS "ROLE_ID_SEQUENCE";

CREATE SEQUENCE "USER_ID_SEQUENCE"
    START WITH 1000
    INCREMENT BY 1;

CREATE SEQUENCE "ROLE_ID_SEQUENCE"
    START WITH 1000
    INCREMENT BY 1;

CREATE TABLE "ROLES"
(
    "ID" BIGINT DEFAULT NEXT VALUE FOR "ROLE_ID_SEQUENCE" PRIMARY KEY,
    "NAME" VARCHAR(30) NOT NULL
);

CREATE TABLE "USERS"
(
    "ID" BIGINT DEFAULT NEXT VALUE FOR "USER_ID_SEQUENCE" PRIMARY KEY,
    "EMAIL" VARCHAR(50),
    "PASSWORD" VARCHAR(120),
    "USERNAME" VARCHAR(20)
);

ALTER TABLE "USERS"
    ADD CONSTRAINT "UK_USERS_USERNAME" UNIQUE ("USERNAME");

ALTER TABLE "USERS"
    ADD CONSTRAINT "UK_USERS_EMAIL" UNIQUE ("EMAIL");

CREATE TABLE "USER_ROLES"
(
    "USER_ID" BIGINT NOT NULL,
    "ROLE_ID" BIGINT NOT NULL,
    PRIMARY KEY ("USER_ID", "ROLE_ID"),
    CONSTRAINT "FK_USER_ROLES_USER"
        FOREIGN KEY ("USER_ID")
            REFERENCES "USERS" ("ID"),
    CONSTRAINT "FK_USER_ROLES_ROLE"
        FOREIGN KEY ("ROLE_ID")
            REFERENCES "ROLES" ("ID")
);