DROP TABLE IF EXISTS "USER_ROLES";
DROP TABLE IF EXISTS "ROLES";
DROP TABLE IF EXISTS "USERS";
DROP SEQUENCE IF EXISTS "USER_ID_SEQUENCE";
DROP SEQUENCE IF EXISTS "ROLE_ID_SEQUENCE";
CREATE SEQUENCE "USER_ID_SEQUENCE" START WITH 1000 INCREMENT BY 1;
CREATE SEQUENCE "ROLE_ID_SEQUENCE" START WITH 1000 INCREMENT BY 1;
CREATE TABLE "ROLES"
(
   "ID" BIGINT DEFAULT ROLE_ID_SEQUENCE.NEXTVAL PRIMARY KEY,
   "NAME" VARCHAR (30) NOT NULL
);
CREATE TABLE "USERS"
(
   "ID" BIGINT DEFAULT USER_ID_SEQUENCE.NEXTVAL PRIMARY KEY,
   "EMAIL" VARCHAR (50),
   "PASSWORD" VARCHAR (120),
   "USERNAME" VARCHAR (20)
);
ALTER TABLE "USERS" ADD UNIQUE ("USERNAME");
ALTER TABLE "USERS" ADD UNIQUE ("EMAIL");
CREATE TABLE "USER_ROLES"
(
   "USER_ID" BIGINT NOT NULL,
   "ROLE_ID" BIGINT NOT NULL
);
ALTER TABLE "USER_ROLES" ADD PRIMARY KEY
(
   "USER_ID",
   "ROLE_ID"
);
ALTER TABLE "USER_ROLES" ADD FOREIGN KEY ("ROLE_ID") REFERENCES "ROLES" ("ID") NOCHECK;
ALTER TABLE "USER_ROLES" ADD FOREIGN KEY ("USER_ID") REFERENCES "USERS" ("ID") NOCHECK;