DROP TABLE IF EXISTS "BOOK";
DROP SEQUENCE IF EXISTS BOOK_ID_SEQUENCE;
CREATE SEQUENCE BOOK_ID_SEQUENCE START WITH 1000 INCREMENT BY 1;
CREATE TABLE "BOOK"
(
   "ID" BIGINT DEFAULT BOOK_ID_SEQUENCE.NEXTVAL PRIMARY KEY,
   "AUTHOR" VARCHAR (30),
   "ISBN" VARCHAR (13) NOT NULL,
   "NAME" VARCHAR (30) NOT NULL
);
ALTER TABLE "BOOK" ADD UNIQUE ("ISBN");