apiVersion: v1
kind: Service
metadata:
  name: hazelcast-auth-service
spec:
  selector:
    app: auth-service
  ports:
    - name: hazelcast
      port: 5701
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  labels:
    app: auth-service
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8085
      nodePort: 31001
  selector:
    app: auth-service
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  labels:
    app: auth-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: ashutoshsahoo/auth-service:1.0.0
          # imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "200Mi"
              cpu: "200m"
            limits:
              memory: "500Mi"
              cpu: "500m"
          ports:
            - name: http
              containerPort: 8085
            - name: multicast
              containerPort: 5701
          env: #add jwt.secret,validity
            - name: HAZELCAST_SERVICE_NAME
              value: hazelcast-auth-service #change to auth-service
            - name: HAZELCAST_NAMESPACE
              value: default
            - name: HAZELCAST_DISCOVERY_TYPE
              value: kubernetes
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-service/postgres
            - name: SPRING_FLYWAY_LOCATIONS
              value: classpath:db/migration/postgresql
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-db
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-db
                  key: password
